set( GPIOD_DEFAULT_PIN "1" CACHE STRING "Default pin number where 433MHz receiver is connected")
set( GPIOD_DEFAULT_DEVICE "/dev/gpiochip0" CACHE STRING "Default device name where 433MHz receiver is connected")

if( NOT BOARD )
	message(STATUS "Check for board type")
	file(READ "/sys/firmware/devicetree/base/model" MODEL)
	
	string(FIND ${MODEL} "Raspberry" POS)
	if( ${POS} GREATER -1 )
		set(BOARD "RASPBERRYPI")
	else()
		string(FIND ${MODEL} "Orange Pi" POS)
		if( ${POS} GREATER -1 )  	
		  	set(BOARD "ORANGEPI")
		 endif()
	endif()
endif()

message(STATUS "Board: ${BOARD}")
if( "${BOARD}" STREQUAL RASPBERRYPI )
	set(GPIOD_DEFAULT_PIN 17)
elseif( "${BOARD}" STREQUAL ORANGEPI )
	set(GPIOD_DEFAULT_PIN 1)
else()
	message(WARNING "Unknown board ${BOARD}. Using default settings")
endif()
