set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_CONTACT "aquaticus")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libgpiod2, libmosquittopp1")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "433MHz temperature and humidity sensor receiver that integrates with home automation systems.")
set(CPACK_DEBIAN_PACKAGE_SECTION "misc")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/aquaticus/nexus433")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
